# Generated by Django 3.0.8 on 2020-07-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_by_zipcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juliandate',
            name='julianDate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='your_zipcode',
            field=models.IntegerField(default=0),
        ),
    ]
