# Generated by Django 3.0.8 on 2020-07-01 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_by_zipcode', '0002_auto_20200701_1933'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JulianDate',
        ),
        migrations.AddField(
            model_name='zipcode',
            name='julianDate',
            field=models.IntegerField(default=0),
        ),
    ]
