# Generated by Django 3.0.8 on 2020-07-01 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_by_zipcode', '0003_auto_20200701_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zipcode',
            name='julianDate',
        ),
        migrations.AddField(
            model_name='zipcode',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
