# Generated by Django 3.0.8 on 2020-07-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_by_zipcode', '0004_auto_20200701_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipcode',
            name='feels_like',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zipcode',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zipcode',
            name='pressure',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='zipcode',
            name='temp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='zipcode',
            name='temp_max',
            field=models.FloatField(default=0),
        ),
    ]
